# Generated by Django 3.2.5 on 2021-07-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_price_variation_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=20),
            preserve_default=False,
        ),
    ]
